version: "3.9"
services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_DB: concert_curator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  # app:
  #   depends_on:
  #     - db
  #   build:
  #     context: ./
  #     target: tests
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_DATABASE: concert_curator
  #     DB_USER: admin
  #     DB_PASSWORD: admin
